### ISSUE TITLE
How to create the GetRequest to get the report information?

### ISSUE THREAD

**Issue by IrisLiqueur** [RallyTools/RallyRestToolkitForJava#18]
RallyRestApi restApi = new RallyRestApi(new URI("https://rally1.rallydev.com"), "", "");
    	String applicationName = "Test Rally API";
        restApi.setApplicationName(applicationName);
        restApi.setProxy(new URI("https://web-proxy.atl.hp.com:8080"), "", "");
        System.out.println(restApi.getWsapiVersion()); 

        
        HttpClient client = restApi.getClient();
        System.out.println(client);
        
        try {
        	SSLSocketFactory sf = new SSLSocketFactory(new TrustStrategy() {
                public boolean isTrusted(X509Certificate[] certificate, String authType)
                    throws CertificateException {
                    //trust all certs
                    return true;
                }
            }, SSLSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER);
            client.getConnectionManager().getSchemeRegistry().register(new Scheme("https", 443, sf));
            
        	String workspaceRef = "/workspace/3724843318"; //YOUR VALID WORKSPACE OID HERE
        	GetRequest getRequest = new GetRequest(workspaceRef);
        	GetResponse getResponse = restApi.get(getRequest);
        	System.out.println(getResponse.getObject());
        } catch (Exception e) {
        	System.out.println(e);
        } finally {
            restApi.close();
        }   

I also find connection problem, timed out...

**Comment by kenshinji** [comment]
What's the output from your console? Is there any error?

**Comment by IrisLiqueur** [comment]
org.apache.http.conn.HttpHostConnectException: Connection to https://rally1.rallydev.com refused


when I set proxy, the error becomes javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated


please help me debug , I want to use it to get information about report sprint time sheet…

**Comment by IrisLiqueur** [comment]
Excuse me , what’s excatly my problem, the connection is refused  or the structure of requrest is wrong>

**Comment by IrisLiqueur** [comment]
RallyRestApi restApi = new RallyRestApi(new URI("https://rally1.rallydev.com"), "userName", "password");
    String applicationName = "Test Rally API";
        restApi.setApplicationName(applicationName);
String workspaceRef = "/workspace/3724843318"; //YOUR VALID WORKSPACE OID HERE
           GetRequest getRequest = new GetRequest(workspaceRef);
           GetResponse getResponse = restApi.get(getRequest);
           System.out.println(getResponse.getObject());


The console is as follows:
v2.0
com.rallydev.rest.client.BasicAuthClient@17a7cec2
Exception in thread "main" org.apache.http.conn.HttpHostConnectException: Connection to https://rally1.rallydev.com refused
     at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:190)
     at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
     at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:643)
     at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
     at org.apache.http.impl.client.DecompressingHttpClient.execute(DecompressingHttpClient.java:137)
     at org.apache.http.impl.client.DecompressingHttpClient.execute(DecompressingHttpClient.java:108)
     at com.rallydev.rest.client.HttpClient.executeRequest(HttpClient.java:157)
     at com.rallydev.rest.client.HttpClient.doRequest(HttpClient.java:145)
     at com.rallydev.rest.client.BasicAuthClient.doRequest(BasicAuthClient.java:56)
     at com.rallydev.rest.client.HttpClient.doGet(HttpClient.java:221)
     at com.rallydev.rest.RallyRestApi.get(RallyRestApi.java:195)
     at rally.test.main(test.java:62)
Caused by: java.net.ConnectException: Connection timed out: connect
     at java.net.DualStackPlainSocketImpl.connect0(Native Method)
     at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
     at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
     at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
     at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
     at java.net.PlainSocketImpl.connect(Unknown Source)
     at java.net.SocksSocketImpl.connect(Unknown Source)
     at java.net.Socket.connect(Unknown Source)
     at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
     at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:414)
     at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
     ... 12 more

**Comment by IrisLiqueur** [comment]
Excuse me , please give my answer as quickly as possible…

**Comment by klehman-rally** [comment]
Make sure that all elements of your stack (libraries, proxies) are using TLS v1 or better.  Some elements of the Rally SaaS infrastructure have been updated over the last couple of months and we've received some isolated reports of transient connectivity problems.  Is the connection refusal you are seeing a consistent behavior?  If so and all your stack is up to date and using TLS, you may want to contact Rally support with information that will assist them in any investigation (like your IP address, date/time window, OS version, JRE vendor/version, etc.).
