### ISSUE TITLE
Connection Exception

### ISSUE THREAD

**Issue by Qijiang60** [RallyTools/RallyRestToolkitForJava#27]
Got following error message when I try to do:
request.setFetch(new Fetch(new String[] {"UserName"}));
QueryResponse response = restApi.query(request);
Exception in thread "main" java.net.UnknownHostException: rally1.rallydev.com
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$1.lookupAllHostAddr(Unknown Source)
	at java.net.InetAddress.getAddressesFromNameService(Unknown Source)
	at java.net.InetAddress.getAllByName0(Unknown Source)
	at java.net.InetAddress.getAllByName(Unknown Source)
	at java.net.InetAddress.getAllByName(Unknown Source)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.resolveHostname(DefaultClientConnectionOperator.java:278)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:162)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:643)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.DecompressingHttpClient.execute(DecompressingHttpClient.java:137)
	at org.apache.http.impl.client.DecompressingHttpClient.execute(DecompressingHttpClient.java:108)
	at com.rallydev.rest.client.HttpClient.executeRequest(HttpClient.java:157)
	at com.rallydev.rest.client.HttpClient.doRequest(HttpClient.java:145)
	at com.rallydev.rest.client.ApiKeyClient.doRequest(ApiKeyClient.java:37)
	at com.rallydev.rest.client.HttpClient.doGet(HttpClient.java:221)
	at com.rallydev.rest.RallyRestApi.query(RallyRestApi.java:172)
	at testing.GetAllUsers.main(GetAllUsers.java:41)

**Comment by krmorse** [comment]
It sounds like it can't resolve your server.  What does your code look like where you instantiated the RallyRestApi object?  The server should include the protocol- "https://rally1.rallydev.com", or if you are an on-prem customer then it should be your internal server url...

**Comment by Qijiang60** [comment]
import com.google.gson.JsonObject;
import com.rallydev.rest.RallyRestApi;
import com.rallydev.rest.request.QueryRequest;
import com.rallydev.rest.response.QueryResponse;
import com.rallydev.rest.util.Fetch;
import java.net.URI;


public class GetAllUsers {
	
	public static void main(String[] args) throws Exception {

		String host = "https://rally1.rallydev.com";
		String apiKey = "_abc123";
               String applicationName = "get all users";
        
        RallyRestApi restApi = null;
		try {
			restApi = new RallyRestApi(new URI(host),apiKey);
	        QueryRequest request = new QueryRequest("User");
	        restApi.setApplicationName(applicationName);  
	        request.setFetch(new Fetch(new String[] {"UserName"}));
	        request.setLimit(1000);
	        //request.setQueryFilter(((new QueryFilter("CreationDate", "<", "2014-01-01").and(new QueryFilter("LastLoginDate","=",null))).or(new QueryFilter("LastLoginDate", "<", "2014-11-01"))).and(new QueryFilter("Disabled","=","false")));
	        
	        QueryResponse response = restApi.query(request);
	        System.out.println("TotalResultCount: " + response.getTotalResultCount());
	        
	        for (int i=0; i<response.getTotalResultCount();i++){
	        	JsonObject userJsonObject = response.getResults().get(i).getAsJsonObject();
	        	System.out.println("Name: " + userJsonObject.get("UserName"));
			}
	        
	        
		} finally {
			if (restApi != null) {
				restApi.close();
			}
		}
	}
}

**Comment by krmorse** [comment]
That code generally looks good to me...  Is it possible you are behind a proxy on your network?  If so you can configure that using the setProxy method before making your first query...

**Comment by Qijiang60** [comment]
You mean put:
RallyRestApi restApiproxy = null;
restApiproxy.setProxy(new URI("http://myproxy.mycompany.com"), "Username", "Password");
before:
        QueryRequest request = new QueryRequest("User");
Please advise...

**Comment by krmorse** [comment]
yes, pretty much that exactly.  just once, before your first api call.  right after the RallyRestApi constructor.

**Comment by Qijiang60** [comment]
Yeah it works. Thanks.
